### ISSUE TITLE
[NEW-MANAGER] Christopher Ton Workshop Task

### ISSUE THREAD

**Issue by kavuong** [bitprj/mdx-deck#39]
Goal: create a 30-60 minute interactive, fun and relatable presentation in MDX-Deck, on any set of modules covered on our road map in this topic: Data Science

**Presentation Day**: Sat, Apr 18

**Comment by chriztopherton** [comment]
link to mdx: https://codesandbox.io/s/bold-cherry-ozur4?file=/decks/c19_ipynb.mdx
